services:
  postgres:
    image: postgres:16
    container_name: colonoscopy_postgres
    environment:
      POSTGRES_USER: colonoscopy_user
      POSTGRES_PASSWORD: colonoscopy_password
      POSTGRES_DB: colonoscopy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: